//TO REQUEST API
export const API_REQUEST='API_REQUEST'



//------------------To show the loading state in UI
export const SHOW_LOADER="SHOW_LOADER"
export const HIDE_LOADER="HIDE_LOADER"
export const REMOVE_ERROR="REMOVE_ERROR"

//----------------- To gain the DEVICE UNIQUE ID
export const GET_DEVICE_INFO_START="GET_DEVICE_INFO_START"
export const GET_DEVICE_INFO_SUCCESS="GET_DEVICE_INFO_SUCCESS"
export const GET_DEVICE_INFO_FAIL="GET_DEVICE_INFO_FAIL"
export const INSERT_DEVICE_INFO="INSERT_DEVICE_INFO"


//------------LOGIN PROCESS-----------------------------------
export const LOGIN_START="LOGIN_START"
export const SOCIAL_LOGIN_START="SOCIAL_LOGIN_START"
export const UPDATE_LOGIN_DATA_SUCCESS="UPDATE_LOGIN_DATA"
export const UPDATE_LOGIN_DATA_FAIL="UPDATE_LOGIN_DATA_FAIL"
export const LOGIN_SUCCESS="LOGIN_SUCCESS"
export const LOGIN_FAIL="LOGIN_FAIL"

//------------Types PROCESS-----------------------------------
export const TYPES_START="TYPES_START"
export const UPDATE_TYPES_DATA_SUCCESS="UPDATE_TYPES_DATA"
export const UPDATE_TYPES_DATA_FAIL="UPDATE_TYPES_DATA_FAIL"
export const TYPES_SUCCESS="TYPES_SUCCESS"
export const TYPES_FAIL="TYPES_FAIL"


//------------REGISTER PROCESS-----------------------------------
export const REGISTER_START="REGISTER_START"
export const REGISTER_SUCCESS="REGISTER_SUCCESS"
export const REGISTER_FAIL="REGISTER_FAIL"
export const UPDATE_REGISTER="UPDATE_REGISTER_DATA"
export const UPDATE_REGISTER_DATA_FAIL="UPDATE_REGISTER_FAIL_DATA"

//------------REGISTER INSTRUCTOR PROCESS-----------------------------------
export const REGISTER_INSTRUCTOR_START="REGISTER_INSTRUCTOR_START"
export const REGISTER_INSTRUCTOR_SUCCESS="REGISTER_INSTRUCTOR_SUCCESS"
export const REGISTER_INSTRUCTOR_FAIL="REGISTER_INSTRUCTOR_FAIL"
export const UPDATE_REGISTER_INSTRUCTOR="UPDATE_REGISTER_INSTRUCTOR_DATA"
export const UPDATE_REGISTER_INSTRUCTOR_DATA_FAIL="UPDATE_REGISTER_INSTRUCTOR_FAIL_DATA"

//------------REGISTER OTP PROCESS-----------------------------------
export const REGISTER_OTP_START="REGISTER_OTP_START"
export const REGISTER_OTP_SUCCESS="REGISTER_OTP_SUCCESS"
export const REGISTER_OTP_FAIL="REGISTER_OTP_FAIL"
export const UPDATE_REGISTER_OTP="UPDATE_REGISTER_OTP_DATA"
export const UPDATE_REGISTER_OTP_DATA_FAIL="UPDATE_REGISTER_OTP_FAIL_DATA"

//------------OTP VERIFIY PROCESS-----------------------------------
export const OTP_VERIFY_START="OTP_VERIFY_START"
export const OTP_VERIFY_SUCCESS="OTP_VERIFY_SUCCESS"
export const OTP_VERIFY_FAIL="OTP_VERIFY_FAIL"
export const UPDATE_OTP_VERIFY="UPDATE_OTP_VERIFY_DATA"
export const UPDATE_OTP_VERIFY_DATA_FAIL="UPDATE_OTP_VERIFY_FAIL_DATA"

//------------GET COURSES PROCESS-----------------------------------
export const GET_COURSES_START="GET_COURSES_START"
export const GET_COURSES_SUCCESS="GET_COURSES_SUCCESS"
export const GET_COURSES_FAIL="GET_COURSES_FAIL"
export const UPDATE_GET_COURSES="UPDATE_GET_COURSES_DATA"
export const UPDATE_GET_COURSES_DATA_FAIL="UPDATE_GET_COURSES_FAIL_DATA"

//------------GET CATEGORIES PROCESS-----------------------------------
export const GET_CATEGORIES_START="GET_CATEGORIES_START"
export const GET_CATEGORIES_SUCCESS="GET_CATEGORIES_SUCCESS"
export const GET_CATEGORIES_FAIL="GET_CATEGORIES_FAIL"
export const UPDATE_GET_CATEGORIES="UPDATE_GET_CATEGORIES_DATA"
export const UPDATE_GET_CATEGORIES_DATA_FAIL="UPDATE_GET_CATEGORIES_FAIL_DATA"

//------------GET BANNERS PROCESS-----------------------------------
export const GET_BANNERS_START="GET_BANNERS_START"
export const GET_BANNERS_SUCCESS="GET_BANNERS_SUCCESS"
export const GET_BANNERS_FAIL="GET_BANNERS_FAIL"
export const UPDATE_GET_BANNERS="UPDATE_GET_BANNERS_DATA"
export const UPDATE_GET_BANNERS_DATA_FAIL="UPDATE_GET_BANNERS_FAIL_DATA"

//------------GET CARTCOUNT PROCESS-----------------------------------
export const GET_CARTCOUNT_START="GET_CARTCOUNT_START"
export const GET_CARTCOUNT_SUCCESS="GET_CARTCOUNT_SUCCESS"
export const GET_CARTCOUNT_FAIL="GET_CARTCOUNT_FAIL"
export const UPDATE_GET_CARTCOUNT="UPDATE_GET_CARTCOUNT_DATA"
export const UPDATE_GET_CARTCOUNT_DATA_FAIL="UPDATE_GET_CARTCOUNT_FAIL_DATA"

//------------GET CARTS PROCESS-----------------------------------
export const GET_CARTS_START="GET_CARTS_START"
export const GET_CARTS_SUCCESS="GET_CARTS_SUCCESS"
export const GET_CARTS_FAIL="GET_CARTS_FAIL"
export const UPDATE_GET_CARTS="UPDATE_GET_CARTS_DATA"
export const UPDATE_GET_CARTS_DATA_FAIL="UPDATE_GET_CARTS_FAIL_DATA"

//------------ADD CARTS PROCESS-----------------------------------
export const ADD_CARTS_START="ADD_CARTS_START"
export const ADD_CARTS_SUCCESS="ADD_CARTS_SUCCESS"
export const ADD_CARTS_FAIL="ADD_CARTS_FAIL"
export const UPDATE_ADD_CARTS="UPDATE_ADD_CARTS_DATA"
export const UPDATE_ADD_CARTS_DATA_FAIL="UPDATE_ADD_CARTS_FAIL_DATA"

//------------DELETE CARTS PROCESS-----------------------------------
export const DELETE_CARTS_START="DELETE_CARTS_START"
export const DELETE_CARTS_SUCCESS="DELETE_CARTS_SUCCESS"
export const DELETE_CARTS_FAIL="DELETE_CARTS_FAIL"
export const UPDATE_DELETE_CARTS="UPDATE_DELETE_CARTS_DATA"
export const UPDATE_DELETE_CARTS_DATA_FAIL="UPDATE_DELETE_CARTS_FAIL_DATA"

//------------GET CARTS PROCESS-----------------------------------
export const GET_COURSE_DETAIL_START="GET_COURSE_DETAIL_START"
export const GET_COURSE_DETAIL_SUCCESS="GET_COURSE_DETAIL_SUCCESS"
export const GET_COURSE_DETAIL_FAIL="GET_COURSE_DETAIL_FAIL"
export const UPDATE_COURSE_DETAIL="UPDATE_COURSE_DETAIL_DATA"
export const UPDATE_COURSE_DETAIL_DATA_FAIL="UPDATE_COURSE_DETAIL_FAIL_DATA"

//------------ADD WISHLIST PROCESS-----------------------------------
export const ADD_WISHLIST_START="ADD_WISHLIST_START"
export const ADD_WISHLIST_SUCCESS="ADD_WISHLIST_SUCCESS"
export const ADD_WISHLIST_FAIL="ADD_WISHLIST_FAIL"
export const UPDATE_ADD_WISHLIST="UPDATE_ADD_WISHLIST_DATA"
export const UPDATE_ADD_WISHLIST_DATA_FAIL="UPDATE_ADD_WISHLIST_FAIL_DATA"

//------------GET WISHLIST PROCESS-----------------------------------
export const GET_WISHLIST_START="GET_WISHLIST_START"
export const GET_WISHLIST_SUCCESS="GET_WISHLIST_SUCCESS"
export const GET_WISHLIST_FAIL="GET_WISHLIST_FAIL"
export const UPDATE_GET_WISHLIST="UPDATE_GET_WISHLIST_DATA"
export const UPDATE_GET_WISHLIST_DATA_FAIL="UPDATE_GET_WISHLIST_FAIL_DATA"

//------------DELETE WISHLIST PROCESS-----------------------------------
export const DELETE_WISHLIST_START="DELETE_WISHLIST_START"
export const DELETE_WISHLIST_SUCCESS="DELETE_WISHLIST_SUCCESS"
export const DELETE_WISHLIST_FAIL="DELETE_WISHLIST_FAIL"
export const UPDATE_DELETE_WISHLIST="UPDATE_DELETE_WISHLIST_DATA"
export const UPDATE_DELETE_WISHLIST_DATA_FAIL="UPDATE_DELETE_WISHLIST_FAIL_DATA"
