export default {
  Student: 'student',
  Instructor: 'instructor',
  cities: [
    'Al Asimah',
    'Hawalli',
    'Mishref',
    'Qadesiya',
    'Safat',
    'Salmiya',
    'al-Ahmadi',
    'al-Farwaniyah',
    'al-Jahra',
    'al-Kuwayt',
    'Bayan',
    'Massilah',
    'Mushrif',
    'Salwa',
    "Sha''ab",
    'Subbah-as-Salim',
    'al-Funaytis',
    'al-Funaytis-al-Garbiyah',
    'al-Jabiriyah',
    'al-Karim',
    'ar-Rumaythiyah',
    'as-Salimiyah',
    "A'qaylah",
    'Abu Hulayfah',
    'Dahar',
    'Desert Area',
    'Hadiyah',
    "Jabbar-al-'Ali",
    "Shu'aybah",
    'al-Fintas',
    'al-Fuhayhil',
    'al-Mahbulah',
    'al-Manqaf',
    'al-Wafrah',
    'ar-Riqqah',
    'as-Sabahiyah',
    'az-Zawr',
    "'Umayriyah",
    'Abraq Khitan',
    'Ardiyah',
    'Fardaws',
    'Jalib ash-Shuyuh',
    'Khitan-al-Janubiyah',
    'Qartaba',
    'Ray',
    'Riqay',
    'Sabhan',
    'Sarbah-an-Nasr',
    'Warmawk',
    'al-Andalus',
    'ar-Rabbiyah',
    'Amgarah',
    'Nasim',
    "Tayma'",
    'Uyawn',
    'Waha',
    'al-Qusayr',
    'as-Sulaybiyah',
    "'Abullah-as-Salam",
    'Ardhiyah',
    'Banayd-al-Qar',
    'Health District',
    'Kayfan',
    'Khalidiyah',
    'Mansuriyah',
    'Nuzha',
    'Qarnadah',
    'Shamiyah',
    "ad-Da'iyah",
    'ad-Dasma',
    'ad-Dawhah',
    "al-'Udayliyah",
    'al-Fayha',
    'al-Qadisiyah',
    'ar-Rawdah',
    'as-Sulaybihat',
    'ash-Shuwaykh Industrial',
    'ash-Shuwaykh Reservoir',
    'Abu Fataira',
    'West Abdullah Al Mubarak',
    'Jaber Al Ahmad',
    'Zahra',
    'Hateen',
    'Shuhada',
    'Al-Siddeeq',
    'Salam',
    'Saad Al Abdullah',
  ],
};
