export default {
  MetropolisBlack: 'Metropolis-Black',
  MetropolisBlackItalic: 'Metropolis-BlackItalic',
  MetropolisBold: 'Metropolis-Bold',
  MetropolisBoldItalic: 'Metropolis-BoldItalic',
  MetropolisExtraBold: 'Metropolis-ExtraBold',
  MetropolisExtraBoldItalic: 'Metropolis-ExtraBoldItalic',
  MetropolisMediumItalic: 'Metropolis-MediumItalic',
  MetropolisMedium: 'Metropolis-Medium',
  MetropolisLightItalic: 'Metropolis-LightItalic',
  MetropolisLight: 'Metropolis-Light',
  MetropolisExtraLightItalic: 'Metropolis-ExtraLightItalic',
  MetropolisExtraLight: 'Metropolis-ExtraLight',
  MetropolisRegular: 'Metropolis-Regular',
  MetropolisRegularItalic: 'Metropolis-RegularItalic',
  MetropolisSemiBold: 'Metropolis-SemiBold',
  MetropolisSemiBoldItalic: 'Metropolis-SemiBoldItalic',
  MetropolisThin: 'Metropolis-Thin',
  MetropolisThinItalic: 'Metropolis-ThinItalic',
};
